USER_OBJS += ./font.o

font.o: ../font.bin
	arm-none-eabi-objcopy \
		-I binary \
		-O elf32-littlearm \
		-B arm \
		--rename-section .data=.rodata,alloc,load,readonly,data,contents \
		--redefine-sym _binary____font_bin_start=font \
		$< $@
